// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmhzazdnqdaavnsooedt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptaHphemRucWRhYXZuc29vZWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTYxOTEsImV4cCI6MjA2OTA5MjE5MX0.9Gs7ZXByj-qgBY0Ww1J6n-xqseCPT3UIrTobTn5MzNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});